export const rowTypes = [
    'SET_FIRST_ROW_CURRENT',
    'SET_SECOND_ROW_CURRENT',
    'SET_THIRD_ROW_CURRENT',
    'SET_FOURTH_ROW_CURRENT',
    'SET_FIFTH_ROW_CURRENT',
    'SET_SIXTH_ROW_CURRENT',
]

export const checkRows = [
    'FIRST_ROW_CHECK',
    'SECOND_ROW_CHECK',
    'THIRD_ROW_CHECK',
    'FOURTH_ROW_CHECK',
    'FIFTH_ROW_CHECK',
    'SIXTH_ROW_CHECK',
]